### PR TITLE
NewYorkTimes_clone_page

### PR DESCRIPTION
**Pull request by Takhmina175**
Based on received feedback the following changes were applied:
using a button to wrap the text, 
using positioning to fix the navbar position
using a cursor, to put the link tags for the articles and wrap the image and the title. 
removing the overlap.

### CODE REVIEW

**Review by tirthajyoti-ghosh — CHANGES_REQUESTED** [review]
# Changes required 🛑 

## Impressive progress so far 💪! Thanks for making all the changes 👏.

### However, we need to work on some changes before we can merge.

- First of all, please use the same PR for ALL reviews. Please don't open different PRs for each review, it introduces confusion when reviewing because the context is lost. Please keep this in mind from next time.

- Please fix all linter errors BEFORE submitting your project for code review.

- Please add the fixed footer. It's missing.

  | Source Page	| Clone Page |
  |:---:|:---:|
  |Annotation 2020-09-08 220251|Annotation 2020-09-08 220600|

- Please take care of the extra space here 👇 .

  Annotation 2020-09-08 220828

- There are several errors and warnings reported in your HTML file. Please fix them.

  image

Your project looks absolutely fantastic. Just make these changes and apply for another code review.

Happy coding 👨‍💻 

*Need help? Shoot me a message on Slack - [@Ghosh](https://app.slack.com/client/T47CT8XPG/DRDM6LAQN/user_profile/URB1MHXK6)*
<hr>

**Tirthajyoti Ghosh**

[GitHub](https://github.com/tirthajyoti-ghosh) | [LinkedIn](https://www.linkedin.com/in/tirthajyoti-ghosh/) | [Twitter](https://twitter.com/terrific_ghosh)

**Comment by Takhmina175** [comment]
I have made all the requested corrections.  I have to inform you that I didn't know that I need to use the same  PR for all reviews. Currently, I don't have the saved version of the initial PR when I made the first pull request. Could you please guide me, what I should do in this case?

**Comment by Takhmina175** [comment]
Thank you so much for your feedback, I have made all the requested
corrections.
 I have to inform you that I didn't know that I need to use the same PR for
all reviews.
Currently, I don't have the saved version of the initial PR when I made the
first pull request.
 Could you please guide me, what I should do in this case?

**Review by tirthajyoti-ghosh — CHANGES_REQUESTED** [review]
# Changes required 🛑 

## Impressive progress so far 💪! Thanks for making all the changes 👏.

### However, we need to work on some changes before we can merge.

- Please add the fixed footer. It's missing.

  | Source Page	| Clone Page |
  |:---:|:---:|
  |Annotation 2020-09-08 220251|Annotation 2020-09-08 220600|

Regarding your doubt, you don't have to do anything for now. Just remember to use the same PR from next time.

Your project looks absolutely fantastic. Just make these changes and apply for another code review.

Happy coding 👨‍💻 

*Need help? Shoot me a message on Slack - [@Ghosh](https://app.slack.com/client/T47CT8XPG/DRDM6LAQN/user_profile/URB1MHXK6)*
<hr>

**Tirthajyoti Ghosh**

[GitHub](https://github.com/tirthajyoti-ghosh) | [LinkedIn](https://www.linkedin.com/in/tirthajyoti-ghosh/) | [Twitter](https://twitter.com/terrific_ghosh)

**Review by kevcap — CHANGES_REQUESTED** [review]
# [STATUS] CHANGES REQUIRED♻️


#### Overall the project looks really nice and I can see that you are working hard on it, and don't worry, you're almost done, there are just some required changes that you guys have to implement to proceed:


_Note_: That changes marked as [OPTIONAL] are not required to approve your project, but I strongly recommend that you guys go for that extra mile, in order to get more knowledge and have a better project to add at your portfolio.

## [REQUIRED CHANGES]
- [ ] Please remove those overlappings at the bottom of the page.
image

## [OPTIONAL CHANGES]
**⚠These are mandatory changes, but since It wasn't pointed out earlier, I'll mark them as [OPTIONAL]:**

- [ ] Kindly remember to remove all the unnecessarily repeated CSS code. Keeping your code DRY is an excellent practice that will help you a lot and make your code more professional. (Check this link form better understanding [Good and Bad CSS Practices for Beginners](https://speckyboy.com/good-bad-css-practices/)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)
Take a look at this example:
image
Your HTML will be something like this: 
image
Apply the same logic above in **ALL** those repeated rules listed below:

image

## Summary
✨ Good job centralizing the layout 💯
✨ Well done implementing `flex`, `grid` and `float` ! The layout looks almost the same.
🔧 Please make the required changes and keep up the good work! 

It was a pleasure to review your code!


### Please make the required changes and resubmit for a new code review once you are ready💪

## As always, I wish you all the very best and see you at the top🚀

👨🏻‍💻 **TSE: Kevin Alves**

  

📫 Have any question about this review? Better call Kevin:

<a  href="mailto:kevinalves.js@gmail.com"> gmail</a> [Twitter Follow](https://twitter.com/intent/follow?screen_name=kevinnnmn) [](https://microverse-students.slack.com/team/UT86D3AP4)

**Review by kevcap — APPROVED** [review]
# [STATUS] PROJECT APPROVED 🍾

### I really like your project! Congrats team, you guys did an excellent job, you have my approval to go ahead and merge this pull request!

_**Clean and modular code, following the best practices and the design a looks great, keep it up!**_ 🥇




## As always, I wish you all the very best and see you both at the top🚀


👨🏻‍💻 **TSE: Kevin Alves**

  

📫 Have any question? Better call Kevin:

<a  href="mailto:kevinalves.js@gmail.com"> gmail</a> [Twitter Follow](https://twitter.com/intent/follow?screen_name=kevinnnmn) [](https://microverse-students.slack.com/team/UT86D3AP4)

**Pull request merged**
