### PR TITLE
NewYorkTimes_web-page_clone 

### PR DESCRIPTION
**Pull request by Takhmina175**

### CODE REVIEW

**Review by SpaYco — CHANGES_REQUESTED** [review]
# Invalid 🛑 



## Sorry, but your project can't be reviewed, you don't have a README ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_readme.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/)) and your Pull Request is not descriptive ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/)), fix that and request another review


Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

**Comment by Takhmina175** [comment]
Thank you for your prompt response, Can I update the Readme file using existing template? could you please guide me in this regards?

**Comment by SpaYco** [comment]
> Thank you for your prompt response, Can I update the Readme file using existing template? could you please guide me in this regards?

yes of course, here's a [Template](https://github.com/microverseinc/readme-template)

and you can learn about how GitHub Markdown works [here](https://guides.github.com/features/mastering-markdown/)

don't hesitate if you need any more help

**Comment by Takhmina175** [comment]
could you please guide me how to create Live-Demo link for my project?

**Comment by SpaYco** [comment]
> could you please guide me how to create Live-Demo link for my project?

you can use https://raw.githack.com/, simply paste the index.html link (the html link, not the repo) and copy the development link (the right one) and there you go

**Comment by SpaYco** [comment]
you've already made a live demo with github-pages though: https://takhmina175.github.io/NewYorkTimes_Clone_Page

**Comment by SpaYco** [comment]
don't forget to update your pull request as well

**Comment by Takhmina175** [comment]
Thank You for guiding me!

**Pull request closed without merging**
